### ISSUE TITLE
How to define Neumann boundary condition

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRL#13]
Hello:
I want to know how to define Neumann boundary condition with fenics such as （du/dy=0），are there any examples to refer to,a more easier example?（I didn't understand the example in fenics-manual-2011）.
Thank you for your help!
Best wishes!

**Comment by jerabaul29** [comment]
Hi!

This is not really a question for the scope of this repo, as you point out it is more of a fenics question.

I am actually not a specialist of FEM, the solver was written by M. Kuchta. But basically, you need to either integrate it in the weak formulation or somehow impose it on the boundary of your problem.

If you want to do this kind of changes I recommend that you learn in details how the Finite Elements Method works, see for example:

http://arturo.imati.cnr.it/~marini/didattica/Metodi-engl/Intro2FEM.pdf
