### ISSUE TITLE
symmetric case

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/Cylinder2DFlowControlDRL#14]
@thw1021 the files for the symmetric configuration should be there:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/symmetric_case

If you have any problems please just let me know.

Putting you in copy for reference @mirok .

**Comment by thw1021** [comment]
Yes. Thank you. Will take a test tonight or tomorrow morning.

**Comment by thw1021** [comment]
The can run successfully but I think there are some small problems (The quality of mesh generated by default parameters is not good):
- [These parameters](https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/91023b38dd9cca3a3804761903a376a7460f02c2/symmetric_case/sym_baseline_flow/env.py#L45-L48) are not used for generating mesh.

- `subprocess.call(cmd + constants, shell=True)` should be added to [Here](https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/91023b38dd9cca3a3804761903a376a7460f02c2/symmetric_case/generate_msh.py#L62-L67). So the modifications of geometry parameters can take effect (I am not quite sure).

**Comment by jerabaul29** [comment]
Ok. It is a long time this was used and I have not been involved in running this code. Is it working now? It should be possible to get working with minor changes, since we did produce Fig 7 ^^ .

**Comment by jerabaul29** [comment]
Working now, as the problem was that the first code uploaded had a wrong inflow velocity profile. Closing.
