### ISSUE TITLE
Problem with creating a new mesh

### ISSUE THREAD

**Issue by SashaUgr** [jerabaul29/Cylinder2DFlowControlDRL#15]
Hi Jean,
I want to make a new simulation with jet_angle=5. I'm using the singularity container. When i try to run make_mesh.py it outputs this 

```
Info    : 4821 vertices 9670 elements
Info    : Writing 'mesh/turek_2d.msh'...
Info    : Done writing 'mesh/turek_2d.msh'
Info    : Stopped on Thu Feb 27 20:33:14 2020
Traceback (most recent call last):
  File "/usr/bin/dolfin-convert", line 36, in <module>
    from dolfin_utils.commands import getoutput
ModuleNotFoundError: No module named 'dolfin_utils'
Traceback (most recent call last):
  File "make_mesh.py", line 2, in <module>
    env.resume_env(plot=500, remesh=True)
  File "/home/ugr/Downloads/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/empty_simulation/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/home/ugr/Downloads/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/empty_simulation/../Env2DCylinder.py", line 132, in __init__
    self.start_class(complete_reset=True)
  File "/home/ugr/Downloads/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/empty_simulation/../Env2DCylinder.py", line 190, in start_class
    convert(msh_file, h5_file)
  File "/home/ugr/Downloads/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/empty_simulation/../msh_convert.py", line 15, in convert
    assert os.path.exists(xml_file)
AssertionError
Aborted (core dumped)
```
So It can't import dolfin_utils, but when i try to run 
`python2 -c "import dolfin_utils"`
or 
`python2 -c "from dolfin_utils.commands import getoutput"`
It does not display any errors. I also tried several versions of gmsh, including the one in your archive.

This is the command I ran to setup singularity and gmsh (Using the "built-in" version):
`singularity shell ~/Downloads/fenics-and-more.img -c "export DISPLAY=:0.0 && export PATH="~/Downloads/Cylinder2DFlowControlDRL-master:$PATH" && /bin/bash"`
and the version i downloaded by my own
`shell ~/Downloads/fenics-and-more.img -c "export DISPLAY=:0.0 && export PATH="~/Downloads/gmsh-3.0.6-Linux64/bin:$PATH" && /bin/bash"`

Also want to clarify that there are no problems running single_runner.py with ready-made mesh.

I apologize for distracting you. I would be very grateful for any help!

**Comment by jerabaul29** [comment]
Hi,

Yes, unfortunately the way the container was built was a bit sub optimal, which leads to difficulties when setting up the re-meshing thing.

I see at least 2 possible explanations for your problem:

- a generic problem in how gmsh is set up. See the help I had been providing in these now closed issues:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/4

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/12

and please go several times / make sure that you understand correctly the gmsh related, and use the gmsh provided in this repo (see: https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/master/gmsh ).

Other people have had problems before but got it to work following these discussions :)

- Maybe gmsh is set up correctly, but you modify the code in a way that causes problems. In particular, the code needs that the jets are ordered by increasing value of the angle. So if you change directly here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/fd174085fb8621d6906bfdf394c49776dc5ce515/Cylinder2DFlowControlWithRL/empty_simulation/env.py#L37

this should be taken care of automatically, but if you directly change there (for example, use 4 jets), then you have to make sure order is respected:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/fd174085fb8621d6906bfdf394c49776dc5ce515/Cylinder2DFlowControlWithRL/empty_simulation/env.py#L49

**Comment by jerabaul29** [comment]
@SashaUgr does this work now? :)

**Comment by SashaUgr** [comment]
I think in my case the problem is in old hardware, which is not supported by the libraries you used. Thanks for the help!
