### ISSUE TITLE
about changing the geometry

### ISSUE THREAD

**Issue by turtle-mei** [jerabaul29/Cylinder2DFlowControlDRL#16]
Hi, Mr.Jean,
I want to change the geometry ,change the cylinder to other geometry.Should i change the geometry_2d.template_geo file? and i want to change it directly the shape rather the code .so sorry to distract you .i would be so grateful for any suggestions.

**Comment by jerabaul29** [comment]
Hi,

Yes, basically you will need to change this file as you said, which is basically a scripted description of your geometry in gmsh format:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/master/Cylinder2DFlowControlWithRL/geometry_2d.template_geo

and possibly a bit of this, which is setting up the relevant parameters there:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/master/Cylinder2DFlowControlWithRL/generate_msh.py

I also recommend that you base your work on the more recent code available there:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

Let me know if anything is unclear. You may need to spend a bit of time learning about gmsh at first. Also, gmsh, fenics, and tensorforce are all packages undergoing rapid development, and the code here (and on the parallel repo) is already 2 and 1 years old respective, so if you want to use the latest features of the underlying packages, you may have a bit of porting / small updates to do.

**Comment by turtle-mei** [comment]
I think I know the general idea,thanks for your help! Thank you.

**Comment by turtle-mei** [comment]
hi,
after I changed the geo and parameters,i encountered such a error.
`iUFL can be obtained from https://github.com/MiroK/ufl-interpreter
Make converge initial state for 10000 iterations
--- call init ---
      template = ../geometry_2d.template_geo
      output = mesh/turek_2d.geo
Info    : Running 'gmsh -0 mesh/turek_2d.geo -setnumber width 0.41 -setnumber size_length 0.05 -setnumber jet_width 1 -setnumber box_size 0.05 -setnumber length 2.2 -setnumber bottom_distance 0.2 -setnumber square_size 0.01 -setnumber front_distance 0.2 -setnumber coarse_distance 0.5 -setnumber coarse_size 0.1' [Gmsh 3.0.6, 1 node, max. 1 thread]
Info    : Started on Mon Apr 27 01:48:42 2020
Info    : Reading 'mesh/turek_2d.geo'...
0.199337
0.199337
Info    : Done reading 'mesh/turek_2d.geo'
Info    : Writing 'mesh/turek_2d.geo_unrolled'...
Info    : Done writing 'mesh/turek_2d.geo_unrolled'
Info    : Stopped on Mon Apr 27 01:48:42 2020
Info    : Running 'gmsh -2 -clscale 0.25 mesh/turek_2d.geo_unrolled' [Gmsh 3.0.6, 1 node, max. 1 thread]
Info    : Started on Mon Apr 27 01:48:42 2020
Info    : Reading 'mesh/turek_2d.geo_unrolled'...
Info    : Starting subloop 1 in Line Loop 24 (are you sure about this?)
Info    : Done reading 'mesh/turek_2d.geo_unrolled'
Info    : Finalized high order topology of periodic connections
Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Meshing curve 6 (Line)
Info    : Meshing curve 7 (Line)
Info    : Meshing curve 8 (Line)
Info    : Meshing curve 9 (Line)
Info    : Meshing curve 10 (Line)
Info    : Meshing curve 11 (Line)
Info    : Meshing curve 12 (Line)
Info    : Meshing curve 13 (Line)
Info    : Meshing curve 14 (Line)
Info    : Meshing curve 15 (Line)
Info    : Meshing curve 16 (Line)
Info    : Meshing curve 17 (Line)
Info    : Meshing curve 18 (Line)
Info    : Meshing curve 19 (Line)
Info    : Done meshing 1D (0.009014 s)
Info    : Meshing 2D...
Info    : Meshing surface 21 (Plane, Delaunay)
Info    : Meshing surface 24 (Plane, Delaunay)
Info    : Done meshing 2D (0.505069 s)
Info    : 5913 vertices 11054 elements
Info    : Writing 'mesh/turek_2d.msh'...
Info    : Done writing 'mesh/turek_2d.msh'
Info    : Stopped on Mon Apr 27 01:48:42 2020
Converting from Gmsh format (.msh, .gmsh) to DOLFIN XML format
Expecting 5110 vertices
Found all vertices
Expecting 9810 cells
Found all cells
Traceback (most recent call last):
  File "/usr/bin/dolfin-convert", line 132, in <module>
    main(sys.argv[1:])
  File "/usr/bin/dolfin-convert", line 79, in main
    meshconvert.convert2xml(ifilename, ofilename, iformat=iformat)
  File "/usr/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 1304, in convert2xml
    convert(ifilename, XmlHandler(ofilename), iformat=iformat)
  File "/usr/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 1325, in convert
    gmsh2xml(ifilename, handler)
  File "/usr/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 495, in gmsh2xml
    index = nodes_as_facets[tuple(nodes)]
KeyError: (0, 16)
Aborted
Traceback (most recent call last):
  File "make_mesh.py", line 2, in <module>
    env.resume_env(plot=500, remesh=True)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/../Env2DCylinder.py", line 132, in __init__
    self.start_class(complete_reset=True)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/../Env2DCylinder.py", line 190, in start_class
    convert(msh_file, h5_file)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/../msh_convert.py", line 17, in convert
    mesh = Mesh(xml_file)
  File "/usr/lib/python2.7/dist-packages/dolfin/mesh/meshes.py", line 63, in __init__
    cpp.Mesh.__cppinit__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/mesh.py", line 2074, in __init__
    _mesh.Mesh_swiginit(self, _mesh.new_Mesh(*args))
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to read data from XML file.
*** Reason:  Error while parsing XML with status "Start-end tags mismatch".
*** Where:   This error was encountered inside XMLFile.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2017.2.0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Aborted`
when i commented out the below part code in geometry_2d.template_geo ,it run normally.
`  //  Define jet surfaces
   For i In {0:(n-1)}

      angle = jet_positions[i];
  
      x = (sl)*Cos(angle)+(jet_width/2)*Sin(angle);
      y = (sl)*Sin(angle)+(jet_width/2)*Cos(angle);
      p = newp;
      Point(p) = {x, y, 0, square_size};
      lower_bound[] += {p};

      x0 = (sl)*Cos(angle);
      y0 = (sl)*Sin(angle);
      arch_center = newp;
      Point(arch_center) = {x0, y0, 0, square_size};

      x = (sl)*Cos(angle)-(jet_width/2)*Sin(angle);
      y = (sl)*Sin(angle)-(jet_width/2)*Cos(angle);
      q = newp;
      Point(q) = {x, y, 0, square_size};
      upper_bound[] += {q};
  
      // Draw the piece; p to angle
      l = newl;
      Line(l) = {p, arch_center}; 
      // Let each yet be marked as a different surface
      Physical Line(5+i) = {l};
      square[] += {l};

      // Draw the piece; angle to q
      l = newl;
      Line(l) = {arch_center, q}; 
      // Let each yet be marked as a different surface
      Physical Line(5+i) += {l};
      square[] += {l};
  EndFor`
Is there some problem with my code or other problem?
I apologize for distracting you. I would be very grateful for any help!

**Comment by turtle-mei** [comment]
hi,
I apologize for distracting you. I would be very grateful for any help!
i change the geo and parameters. when i run the code,there are the below error.
 
`Info    : 5913 vertices 11054 elements
Info    : Writing 'mesh/turek_2d.msh'...
Info    : Done writing 'mesh/turek_2d.msh'
Info    : Stopped on Mon Apr 27 01:48:42 2020
Converting from Gmsh format (.msh, .gmsh) to DOLFIN XML format
Expecting 5110 vertices
Found all vertices
Expecting 9810 cells
Found all cells
Traceback (most recent call last):
  File "/usr/bin/dolfin-convert", line 132, in <module>
    main(sys.argv[1:])
  File "/usr/bin/dolfin-convert", line 79, in main
    meshconvert.convert2xml(ifilename, ofilename, iformat=iformat)
  File "/usr/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 1304, in convert2xml
    convert(ifilename, XmlHandler(ofilename), iformat=iformat)
  File "/usr/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 1325, in convert
    gmsh2xml(ifilename, handler)
  File "/usr/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 495, in gmsh2xml
    index = nodes_as_facets[tuple(nodes)]
KeyError: (0, 16)
Aborted
Traceback (most recent call last):
  File "make_mesh.py", line 2, in <module>
    env.resume_env(plot=500, remesh=True)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/../Env2DCylinder.py", line 132, in __init__
    self.start_class(complete_reset=True)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/../Env2DCylinder.py", line 190, in start_class
    convert(msh_file, h5_file)
  File "/home/ivan/Downloads/singularity/singularity-2.5.1/my img/square/empty/../msh_convert.py", line 17, in convert
    mesh = Mesh(xml_file)
  File "/usr/lib/python2.7/dist-packages/dolfin/mesh/meshes.py", line 63, in __init__
    cpp.Mesh.__cppinit__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/mesh.py", line 2074, in __init__
    _mesh.Mesh_swiginit(self, _mesh.new_Mesh(*args))
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to read data from XML file.
*** Reason:  Error while parsing XML with status "Start-end tags mismatch".
*** Where:   This error was encountered inside XMLFile.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2017.2.0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

Aborted`
but when i comment out the part that about define the jet surface in the geometry_2d.template_geo ,it run normally.
i feel so comfused.

**Comment by jerabaul29** [comment]
- Have you ever been able to create any mesh with custom geometry successfully before?

- if yes, have you changed anything regarding the packages used? For example, gmsh or other version?

- Are you sure you use the right gmsh version? You should use the one there: https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/master/gmsh . Other versions may not be compatible. Please check that you well use the gmsh in question, not something else linked by your system.

- have you checked on the other issues if you get the answer to your problems:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/12

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/4

- are you sure that your mesh is 'valid' and well described? Can you mesh directly with gmsh tool in GUI, and display the mesh to check that everything looks good?

**Comment by jerabaul29** [comment]
Other than that, there is not much I can do, as things quickly become machine / installation / case specific.
