### ISSUE TITLE
Can not get the "fenics-and-more.img" file

### ISSUE THREAD

**Issue by sminder-git** [jerabaul29/Cylinder2DFlowControlDRL#18]
Hello,
Thank you for sharing your code for flow control problems, it's very useful for my research. I have been working on setting up the container and I found that I couldn't get the "fenics-and-more.img" file from the following link:
https://folk.uio.no/jeanra/Informatics/fenics-and-more.img
I've tried both curl and wget but neither of them works.
I got the following information:
`sminder@sminder-VirtualBox:~$ wget "https://folk.uio.no/jeanra/Informatics/fenics-and-more.img"
--2020-10-21 18:52:39--  https://folk.uio.no/jeanra/Informatics/fenics-and-more.img
Resolving folk.uio.no (folk.uio.no)... 129.240.118.92, 2001:700:100:118::92
Connecting to folk.uio.no (folk.uio.no)|129.240.118.92|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://folk.universitetetioslo.no/jeanra/Informatics/fenics-and-more.img [following]
--2020-10-21 18:52:40--  https://folk.universitetetioslo.no/jeanra/Informatics/fenics-and-more.img
Resolving folk.universitetetioslo.no (folk.universitetetioslo.no)... 129.240.118.41, 2001:700:100:118::41
Connecting to folk.universitetetioslo.no (folk.universitetetioslo.no)|129.240.118.41|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-21 18:52:40 ERROR 404: Not Found.
`
Is there another method to download this image?

Many thanks.
Shaoze

**Comment by jerabaul29** [comment]
Hi,

Many thanks for your kind words!

The folk.uio.no website has been end of lifed and discontinued. Now the way to get the container image is to use the fragments available on the repo here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/container

Following the readme instructions:

"
The container was committed using git-lfs in several segments, to make sure that the size limit is not over-run. To put the segments together:
> cat fenics-and-more.img_part.?? > fenics-and-more.img
> sha256sum fenics-and-more.img
e6e3c6b24d4edb93022d1156aba1a458367242d0ba1f249508bd2669f87ee4b8  fenics-and-more.img
"

Can you confirm if you are able to make things work this way? :) .

**Comment by jerabaul29** [comment]
I will update the Readme to make things clearer.

**Comment by jerabaul29** [comment]
Updated now. 

PS: consider using the parallelized code instead for increasing training speed:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

And you may be interested also in this follow up study:

https://github.com/thw1021/Cylinder2DFlowControlGeneral

**Comment by sminder-git** [comment]
Hi,

Thank you so much for your quick response, I will try the parallelized code and the git-lfs. I'm looking at flow control applications on an airfoil, which has a more complex mesh but closer to industrial application.  It seems that your approach is very promising to expend to multiple applications!

Thanks again for your kindly guidance.
Shaoze

**Comment by jerabaul29** [comment]
Thanks! Then I close this issue, if you have any problems feel free to either re-open it or open a new separate one. You are welcome :) .
