### ISSUE TITLE
how to downlowd

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRL#2]
well,dear professor!,I want to download the singularity,however ,the website you offered is not avaliable .

**Comment by jerabaul29** [comment]
Not sure what you mean. From my computer, trying to download:

https://folk.uio.no/jeanra/Informatics/fenics-and-more.img

works just fine. You will need to install singularity by yourself.

**Comment by yangtianyong** [comment]
thank you professor!it is working now
