### ISSUE TITLE
New airfoil model encountered mesh convertion probelm

### ISSUE THREAD

**Issue by Shao-hansen** [jerabaul29/Cylinder2DFlowControlDRL#21]
Dear professor,

Thanks you so much for this greak work. I repleaced the Cylinder to a NACA-0012 airfoil. When I converted the mesh by msh_convert.py file.  DOLFIN encountered an error. It seem that DOLFIN can not generate a facet_region.xml, thus can not found this file. Here is the error information:

*** Error:   Unable to read data from XML file.
*** Reason:  Unable to open file "mesh/NACA0012_2D_facet_region.xml".
*** Where:   This error was encountered inside XMLFile.cpp.
*** Process: 0
***
*** DOLFIN version: 2017.2.0
*** Git changeset:  unknown
 
Actually, I am wonderring why to convert the mesh to h5 file and facet_region.xml file from 18 to 26 line in msh_convert.py:

 17     mesh = Mesh(xml_file)
 18     out = HDF5File(mesh.mpi_comm(), h5_file, 'w')
 19     out.write(mesh, 'mesh')
 20 
 21     for region in ('facet_region.xml', ):
 22         name, _ = region.split('_')
 23         r_xml_file = '_'.join([root, region])
 24 
 25         f = MeshFunction('size_t', mesh, r_xml_file)
 26         out.write(f, name)

I have searched the MeshFunction in

https://fenicsproject.org/olddocs/dolfin/latest/python/_autogenerated/dolfin.cpp.mesh.html?highlight=meshfunction#dolfin.cpp.mesh.MeshFunctionSizet

However, I got no answer. And I have tried to email the fenics-support@googlegroups.com for help. But the owner of the group may have removed this group and my email was rejected. 

Looking forward to your help. Thank you so much!

Here is the geo file for NACA0012, It could generate the msh file.

 1 //Scirpt
  2 
  3 Li  = 50.0; Lo  = 50.0; // distance of inflow and outflow boundary from     origin
  4 Li1 = 2.0; Lo1 = 2.0;   // distance of intermediate inflow and outflow f    rom origin
  5 
  6 n  = 100; // points on upper/lower surface of airfoil used to define air    foil
  7          // These points may not appear in the mesh.
  8 
  9 lc1 = 10.0; lc2 = 0.00001; // characteristic lengths of elements on airf    oil and at farfield
 10 lc3 = 0.1; //characteristic length for the inetrmediate domain
 11 m = 2*n - 2; // total number of points on airfoil without repetition
 12              // LE and TE points are common to upper/lower surface
 13 
 14 nle = n; // point number of LE = no. of points on upper surface
 15          // Point(1) is trailing edge
 16 
 17 // NACA0012 profile: formula taken from http://turbmodels.larc.nasa.gov/    naca0012_val.html
 18 Macro NACA0012
 19    x2 = x * x;
 20    x3 = x * x2;
 21    x4 = x * x3;
 22    y = 0.594689181*(0.298222773*Sqrt(x) - 0.127125232*x - 0.357907906*x2     + 0.291984971*x3 - 0.105174606*x4);
 23 Return
 24 
 25 // put points on upper surface of airfoil
 26 For i In {1:n}
 27    theta = Pi * (i-1) / (n-1);
 28    x = 0.5 * (Cos(theta) + 1.0);
 29    Call NACA0012;
 30    Point(i) = {x, y, 0.0, lc2};
 31    xx[i] = x;
 32    yy[i] = y;
 33 EndFor
 34 
 35 // put points on lower surface of airfoil, use upper surface points and     reflect
 36 For i In {n+1:m}
 37    Point(i) = {xx[2*n-i], -yy[2*n-i], 0.0, lc2};
 38 EndFor
 39 
 40 Spline(1) = {1:n}; Spline(2) = {n:m,1};
 41 
 42 Transfinite Line{1,2} = n Using Bump 0.1;
 43 
 44 Point(1001) = { 0.0, Li, 0.0,lc1};
 45 Point(1002) = { 0.0, -Li, 0.0, lc1};
 46 Point(1003) = {Lo, -Li, 0.0, lc1};
 47 Point(1004) = {Lo, Li, 0.0, lc1};
 48 
 49 Line(3) = {1004, 1001};
 50 Circle(4) = {1001, nle, 1002};
 51 Line(5) = {1002, 1003};
 52 Line(6) = {1003, 1004};
 53 
 54 Line Loop(1) = {1,2};
 55 Line Loop(2) = {3,4,5,6};
 56 
 57 //Intermediate Domain
 58 Point(2001) = { 0.0, Li1, 0.0,lc3};
 59 Point(2002) = { 0.0, -Li1, 0.0, lc3};
 60 Point(2003) = {Lo1, -Li1, 0.0, lc3};
 61 Point(2004) = {Lo1, Li1, 0.0, lc3};
 62 
 63 Line(13) = {2004, 2001};
 64 Circle(14) = {2001, nle, 2002};
 65 Line(15) = {2002, 2003};
 66 Line(16) = {2003, 2004};
 67 
 68 Line Loop(3) = {13,14,15,16};
69 
 70 Plane Surface(201) = {3,1};
 71 Plane Surface(202) = {3,2};
 72 
 73 //Extrude {0,0,lc1} { Surface{201,202}; Layers{1}; Recombine;}
 74 
 75 //Define Boundary Layer
 76 Field[1] = BoundaryLayer;
 77 Field[1].EdgesList = {1,2};
 78 Field[1].AnisoMax = 1.0;
 79 Field[1].FanNodesList = {1};
 80 Field[1].hfar = 0.03;
 81 Field[1].hwall_n = 0.001;
 82 Field[1].thickness = 0.05;
 83 Field[1].ratio = 1.1;
 84 Field[1].Quads = 1;
 85 Field[1].IntersectMetrics = 0;
 86 BoundaryLayer Field = 1;
 87 
 88 Physical Surface(201) = {201,202};  //Periodic at z = 0
 89 Physical Surface(202) = {276, 234}; //Periodic at z = lc1
 90 Physical Surface(203) = {271, 275, 263, 267}; //Farfield
 91 //Physical Volume(1)    = {1, 2};
 92 
 93 Mesh 2;
 94 Save "NACA0012_2D.msh";

**Comment by jerabaul29** [comment]
Hi,

I will unfortunately not have the time to debug this for you.

This looks like a pure mesh generation problem. Can you go through the GMSH manual, and make sure that you were able to 1) generate the mesh, 2) with the right faces numbering? GMSH has a standalone application with visualization abilities which is great for inspecting the mesh / checking if a mesh was generated etc.

Good luck!

**Comment by jerabaul29** [comment]
Closing as this is user-specific and an extension work that is different from the cylinder case, for which I unfortunately do not have time to offer "free support".
