### ISSUE TITLE
higher Reynolds problem

### ISSUE THREAD

**Issue by ruyigolden-cudgel** [jerabaul29/Cylinder2DFlowControlDRL#26]
Hi,Sir. I am interested in this work you did, I carefully read your code and articles and lectures on Youtube.I also successfully run your code on linux, and **I try to simulate an new cylinder simulation at **higher Reynolds numbe**r**, so I change the value of **Um** in line 61 of _empty_simulation/env.py_. After trying that, I found that when **Um** exceeds **1.5*1.3** there will be an error in simulation running information,**Rec Area, drag and lift** all three variables are invalid. And I checked the code of _probes.py_ and have no clue, if you still remember the code, can you elaborate? The code running information is in the following：
  
   **Simu_lift | Ep N:    0, step:    0, Rec Area: 0.0977, drag: -2.2200, lift: -0.0144**
/home/triwonsx/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/empty_simulation/../probes.py:325: RuntimeWarning: invalid value encountered in less
  mask = np.where(coefs0 < self.threshold)[0]  # This is local to coefs0 numbering
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
/usr/lib/python2.7/dist-packages/matplotlib/quiver.py:627: RuntimeWarning: Mean of empty slice.
  amean = a[~self.Umask].mean()
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/lib/python2.7/dist-packages/matplotlib/quiver.py:701: RuntimeWarning: invalid value encountered in less
  short = np.repeat(length < minsh, 8, axis=1)
/usr/lib/python2.7/dist-packages/matplotlib/quiver.py:711: RuntimeWarning: invalid value encountered in less
  tooshort = length < self.minlength
/usr/lib/python2.7/dist-packages/matplotlib/colors.py:941: UserWarning: Warning: converting a masked element to nan.
  vmin = float(vmin)
/usr/lib/python2.7/dist-packages/matplotlib/colors.py:942: UserWarning: Warning: converting a masked element to nan.
  vmax = float(vmax)
**Simu_lift | Ep N:    0, step:  100, Rec Area: 0.0000, drag: nan, lift: nan
Simu_lift | Ep N:    0, step:  200, Rec Area: 0.0000, drag: nan, lift: nan
Simu_lift | Ep N:    0, step:  300, Rec Area: 0.0000, drag: nan, lift: nan
Simu_lift | Ep N:    0, step:  400, Rec Area: 0.0000, drag: nan, lift: nan
Simu_lift | Ep N:    0, step:  500, Rec Area: 0.0000, drag: nan, lift: nan**

**Comment by jerabaul29** [comment]
Hi @ruyigolden-cudgel ,

If you change the Re through the velocity, without changing the mesh / numerical timestep, you will likely break the CFL condition and your simulation will diverge. This is likely what the NaN indicate / how they arise.

We have looked at a bit higher Res in the following study:

- https://pubs.aip.org/aip/pof/article-abstract/32/5/053605/1033993/Robust-active-flow-control-over-a-range-of?redirectedFrom=fulltext (also on ArXiv at https://arxiv.org/abs/2004.12417 )
- https://github.com/thw1021/Cylinder2DFlowControlGeneral

As you can see, the Re was changed by changing the value of nu in the code:

https://github.com/thw1021/Cylinder2DFlowControlGeneral/blob/ac5ea7fd304dedefa4489790e45c42ca9428440e/RobustDRLCylinder2DControl/Env2DCylinder.py#L157-L158

I also think we had to tune the mesh (see the different baselines / meshes for the different Re values):

https://github.com/thw1021/Cylinder2DFlowControlGeneral/tree/master/RobustDRLCylinder2DControl/simulation_base

Note that this code is not suited for going much higher in Re than what is done there. We are going quite a bit higher in Re in newer works (for example, see https://www.mdpi.com/2076-0825/11/12/359 ), but that requires using another code. Nowadays I would recommend using another system than this old code, for example see https://github.com/venturi123/DRLinFluids (described in https://pubs.aip.org/aip/pof/article-abstract/34/8/081801/2846652/DRLinFluids-An-open-source-Python-platform-of?redirectedFrom=fulltext , also available on ArXiv at https://arxiv.org/abs/2205.12699 ).

Closing the issue, please see the linked materials.
