### ISSUE TITLE
Download the Singularity container

### ISSUE THREAD

**Issue by lazyaa** [jerabaul29/Cylinder2DFlowControlDRL#27]
Professor,hello, I want to download the singularity, but the download link in the readme and https://folk.universitetetioslo.no/jeanra/Informatics/fenics-and-more.img seems to be unavailable

**Comment by jerabaul29** [comment]
Yes, the container is not hosted there any longer, but as segments on this repository: please see the readme section https://github.com/jerabaul29/Cylinder2DFlowControlDRL#using-through-our-container-recommended , and the following issues where this is discussed:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/18
https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/issues/12

It looks like I get this comment now and then, I guess you got the link during a course or something like this? If some course materials / some supervisors refer you to this link, can you ask them to update their materials to not refer to it any longer, and say to follow the instructions on the readme instead? :)

**Comment by lazyaa** [comment]
thank you
