### ISSUE TITLE
problems about singularity container parts 

### ISSUE THREAD

**Issue by lazyaa** [jerabaul29/Cylinder2DFlowControlDRL#28]
Hello Professor, I want to download the singularity container fragment, but the integrity of the segments is not correct. What is the reason
```

> (base) lzy@lzy-virtual-machine:~$ cd /home/lzy/Cylinder2DFlowControlDRL/container
> (base) lzy@lzy-virtual-machine:~/Cylinder2DFlowControlDRL/container$ cat fenics-and-more.img_part.?? > fenics-and-more.img
> (base) lzy@lzy-virtual-machine:~/Cylinder2DFlowControlDRL/container$ sha256sum fenics-and-more.img
> 141a0faf677f1d24d2e7643a9c763c355a18e34a7ccfc33d7ce4ef65524c004a  fenics-and-more.img
> 
```

**Comment by jerabaul29** [comment]
Looks like one or more of your parts was corrupted during download. This has happened before, see from the readme:

> A note here: while git-lfs should allow to download sucessfully all segments upon cloning the repository, it seems that there is a problem, either with github serving the git-lfs files, or with git checking out the large files. So to get all the fragments, you may have to use the github web GUI, i.e. to 1) go to the right folder (https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/container) 2) for each fragment there, to click on the filename and use the download button to start downloading directly from your browser. Once this is done, you can assemble by:

Have you used this method, and are you sure you have all the parts fully downloaded? This has been used by people in the past, so this should work :) .

**Comment by lazyaa** [comment]
thanks

**Comment by jerabaul29** [comment]
(just for my "records", did it work in the end? :) )
