### ISSUE TITLE
related to value of mean Drag

### ISSUE THREAD

**Issue by Ashut22** [jerabaul29/Cylinder2DFlowControlDRL#29]
why mean drag coffecient value is come too less that (-.4409(approx) while as in many research paper it is mentioned that Drag coffecient value is close 1.34 for Reynolds number  = 100 ??
pls explain this

**Comment by jerabaul29** [comment]
Hi,

- can this be related to https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/3 ? When taking into account the non dimensionalization, the figures match well with the Turek benchmark
- remember that you have to compare to the same benchmark, also regarding the domain width etc - i.e., the results should match specifically the Turek benchmark, not the cylinder in a large free flow configuration.

**Comment by Ashut22** [comment]
then sir please tell me how I  relate mean drag to get my actual value of drag coefficient. because in many research paper value of drag coefficent is 1.35 when we use DRL.
sir please guide me

**Comment by jerabaul29** [comment]
Regarding the drag on a cylinder:

- the drag coefficient depends on the geometry (2D or 3D, channel or open domain, etc), the Re, the closeness to the boundaries, etc.
- for the specific case we look into, i.e. similar to the Turek benchmark, the drag coefficient is as expected (taking into account the link in my first answer to do the non dimensionalization), and many people have reproduced the results in this paper using different solvers from ours, so we are 100% sure about the validity of the results we present in the case we present.

Your question about the "drag value" (which is depends on many factors) is about basic fluid mechanics in general, and this is off topic here - unfortunately I do not have time to offer free teaching in fluid mechanics.

Closing.
