### ISSUE TITLE
 question when made a new mesh

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRL#4]
hello ,i want to make a new simulation of my own.When i run make_mesh.py,here is a mistake . 

iUFL can be obtained from https://github.com/MiroK/ufl-interpreter
Make converge initial state for 10000 iterations
--- call init ---
Traceback (most recent call last):
  File "make_mesh.py", line 2, in <module>
    env.resume_env(plot=False, remesh=True)
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/../Env2DCylinder.py", line 132, in __init__
    self.start_class(complete_reset=True)
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/../Env2DCylinder.py", line 183, in start_class
    generate_mesh(self.geometry_params, template=self.geometry_params['template'])
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/generate_msh.py", line 11, in generate_mesh
    printiv(template)
  File "/usr/local/lib/python2.7/dist-packages/printind/printind_function.py", line 38, in printiv
    string = inspect.getframeinfo(frame[0]).code_context[0].strip()
TypeError: 'NoneType' object has no attribute '__getitem__'
Aborted (core dumped)

it is really appreciated for your help! and i am really sorry to trouble you for a debug question.

**Comment by jerabaul29** [comment]
Hi!

Strange, I had not seen this before.

- Are you using the singularity container?

- What happens if you replace the ```printind``` by a normal ```print``` in **generate_msh.py** line 11 (and possibly at other locations in the code where printind may be called)? This is where the error message points to.

**Comment by jerabaul29** [comment]
Another issue I have seen several times is failure to call **gmsh** from within the program; however at this point it does not look like this is the problem you have.

**Comment by yangtianyong** [comment]
Yes,I used the singularity container.I replaced the printind by a normal print just now,it didn't work.
Here are my steps:  in empty_simulation,i changed jet_angle=5,and then plot=false,last run make_mesh.py.
So I wonder if there are any details i missed.
appreciated your answer

**Comment by jerabaul29** [comment]
What error messages do you obtain replacing the **printind** calls by some **print** calls? Can you show me your terminal output?

**Comment by yangtianyong** [comment]
still the same mistake.

iUFL can be obtained from https://github.com/MiroK/ufl-interpreter
Make converge initial state for 10000 iterations
--- call init ---
Traceback (most recent call last):
  File "make_mesh.py", line 2, in <module>
    env.resume_env(plot=False, remesh=True)
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/../Env2DCylinder.py", line 132, in __init__
    self.start_class(complete_reset=True)
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/../Env2DCylinder.py", line 183, in start_class
    generate_mesh(self.geometry_params, template=self.geometry_params['template'])
  File "/home/yang/Downloads/jet_angle5/Cylinder2DFlowControlWithRL/empty_simulation/generate_msh.py", line 11, in generate_mesh
    print(template)
  File "/usr/local/lib/python2.7/dist-packages/printind/printind_function.py", line 38, in printiv
    string = inspect.getframeinfo(frame[0]).code_context[0].strip()
TypeError: 'NoneType' object has no attribute '__getitem__'
Aborted (core dumped)

**Comment by jerabaul29** [comment]
I am sorry, I do not understand what you did / where the problem is. I know other people managed to change the number and position of jets, and we also did it successfully. Can you turn *plot* to True and see if something changes?

**Comment by jerabaul29** [comment]
sorry, I mean put back **plot=500** .

**Comment by yangtianyong** [comment]
well ,i will have a try .thank you

**Comment by jerabaul29** [comment]
As a side note: other people had problems in the past to get the **gmsh** calls here to work:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/master/Cylinder2DFlowControlWithRL/generate_msh.py#L35

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/master/Cylinder2DFlowControlWithRL/generate_msh.py#L52

This is because, 'stupidly', gmsh is not installed inside the singularity container.

To solve this there are 2 solutions:

- Export the gmsh provided in the repo to the singularity container: this is what is recommended in the Readme: ```export PATH="SET_YOUR_PATH/gmsh-git-Linux64/bin:$PATH```

- Update the two lines listed above to directly execute the gmsh provided in the repo. For this to work, you will need to first do a ```chmod``` to make the gmsh binary executable, and then call it in a ```./``` fashion in the code.

**Comment by yangtianyong** [comment]
Well,with the material you offered,I successfully sovle the problem.

**Comment by jerabaul29** [comment]
Great to hear, many thanks for the update!

For the records, what was the problem / which step solved it? :)

**Comment by yangtianyong** [comment]
There are lots of versions 3.+ about gmsh,maybe some of them are not suitable.So I used 3.0.6 that you talked about in readme.md at last,and it works.
I realize that I shuold  follow your  guideline at the begin,and I can avoid lots of problems.
So kind of you!

**Comment by jerabaul29** [comment]
Ok. Good to know it works when you follow the Readme ;) .
