### ISSUE TITLE
Using Singularity container in windows 10

### ISSUE THREAD

**Issue by tsathishgct** [jerabaul29/Cylinder2DFlowControlDRL#5]
Hi, I've installed Singularity, Gmsh on my windows 10, I also downloaded the singularity container given in https://folk.uio.no/jeanra/Informatics/fenics-and-more.img. But I don't know how to run this container using singularity in windows 10. Online videos are not very explanatory . Kindly help.

Thank you

**Comment by jerabaul29** [comment]
I have not touched a windows system in several years, so I cannot help here.

However, the only thing you need to do is to understand how to issue singularity commands from the windows terminal. Once you are in the singularity container, you are basically on a linux independently of your host machine, so all the readme will work in exactly the same way.

Another possibility is that you get your hand on a linux machine - Ubuntu dual boot or similar, or some web-based service such as AWS - I think they even have 'free 1 year trial' on AWS.

**Comment by tsathishgct** [comment]
Ok Mr.Jean. I'll try to get Linux OS.

**Comment by jerabaul29** [comment]
I also think that using / learning linux is a must for everything related to ML / AI / ANNs nowadays anyways :)
