### ISSUE TITLE
About changing Re

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRL#6]
Hello,i want to use a larger Nu with your code,so i change Um from 1.5 to 4.5 ,Um=4.5,after this ,i think the Nu number is 300.At the same time ,i also change the refinement of the mesh ,dt ,something related.However,when i run make_mesh.py,there is something wrong about the drag results.(the drag results should be close between Nu=100 and Nu=300,and this is mush larger) .
are there any others factors that may cause this problem?
Thank you again!(it is embarrassed for me that lack knowledge in this respect ,please don't mind)
Simu_M005_lift | Ep N:    0, step: 1000, Rec Area: 0.0045, drag: -1.1114, lift: 0.0100
Simu_M005_lift | Ep N:    0, step: 1100, Rec Area: 0.0050, drag: -1.1644, lift: 0.0103
Simu_M005_lift | Ep N:    0, step: 1200, Rec Area: 0.0055, drag: -1.1837, lift: 0.0106
Simu_M005_lift | Ep N:    0, step: 1300, Rec Area: 0.0059, drag: -1.1701, lift: 0.0121
Simu_M005_lift | Ep N:    0, step: 1400, Rec Area: 0.0065, drag: -1.1448, lift: 0.0152
Simu_M005_lift | Ep N:    0, step: 1500, Rec Area: 0.0071, drag: -1.1253, lift: 0.0198
Simu_M005_lift | Ep N:    0, step: 1600, Rec Area: 0.0078, drag: -1.1147, lift: 0.0255
Simu_M005_lift | Ep N:    0, step: 1700, Rec Area: 0.0086, drag: -1.1090, lift: 0.0318
Simu_M005_lift | Ep N:    0, step: 1800, Rec Area: 0.0090, drag: -1.1046, lift: 0.0383
Simu_M005_lift | Ep N:    0, step: 1900, Rec Area: 0.0096, drag: -1.0996, lift: 0.0448
Simu_M005_lift | Ep N:    0, step: 2000, Rec Area: 0.0100, drag: -1.0931, lift: 0.0514
Simu_M005_lift | Ep N:    0, step: 2100, Rec Area: 0.0106, drag: -1.0850, lift: 0.0579
Simu_M005_lift | Ep N:    0, step: 2200, Rec Area: 0.0113, drag: -1.0757, lift: 0.0640
Simu_M005_lift | Ep N:    0, step: 2300, Rec Area: 0.0113, drag: -1.0663, lift: 0.0690
Simu_M005_lift | Ep N:    0, step: 2400, Rec Area: 0.0119, drag: -1.0575, lift: 0.0727
Simu_M005_lift | Ep N:    0, step: 2500, Rec Area: 0.0122, drag: -1.0500, lift: 0.0742
Simu_M005_lift | Ep N:    0, step: 2600, Rec Area: 0.0127, drag: -1.0437, lift: 0.0728
Simu_M005_lift | Ep N:    0, step: 2700, Rec Area: 0.0130, drag: -1.0382, lift: 0.0677
Simu_M005_lift | Ep N:    0, step: 2800, Rec Area: 0.0132, drag: -1.0332, lift: 0.0585
Simu_M005_lift | Ep N:    0, step: 2900, Rec Area: 0.0140, drag: -1.0287, lift: 0.0448
Simu_M005_lift | Ep N:    0, step: 3000, Rec Area: 0.0141, drag: -1.0245, lift: 0.0263
Simu_M005_lift | Ep N:    0, step: 3100, Rec Area: 0.0144, drag: -1.0207, lift: 0.0031

**Comment by jerabaul29** [comment]
No worries.

- I think you mean Re not nu?

- Indeed you need to adapt the mesh and dt (because of the CFL condition). Also check that your mesh is fine enough with a refinement study.

- You need to remember that CD is drag / (0.5 rho Um^2 D), so if you change Re through Um you will have to adapt the scaling factor (here you divide by 3^2 = 9).

Does the last point fixes your problem?

**Comment by jerabaul29** [comment]
PS: see Eqn. 2 of https://arxiv.org/abs/1808.07664 in latest version if I remember well.

**Comment by yangtianyong** [comment]
i made a mistake ,i mean Re，it is really useful for my  problem .
thank you

**Comment by jerabaul29** [comment]
Seems this is ok now then, so closing. If you have more questions about this topic you can just re-open.
