### ISSUE TITLE
Using Dolphin Expression 

### ISSUE THREAD

**Issue by DonsetPG** [jerabaul29/Cylinder2DFlowControlDRL#9]
Hello,

With the Fenics version available on their official Docker container, it seems that your definition of ```python JetBCValue ``` is outdated because your are building it on top of an ```python Expression ``` : 

```python
class JetBCValue(Expression):

    def __init__(self, radius, width, theta0, Q, **kwargs):
        assert width > 0 and radius > 0
        theta0 = np.deg2rad(theta0)
        assert theta0 >= 0 
        self.radius = radius
        self.width = np.deg2rad(width)
        self.theta0 = normalize_angle(theta0)

        self.Q = Q
```

It seems that you need to pass a UserExpression to make it work : 

```python

class JetBCValue(UserExpression):


    def __init__(self, radius, width, theta0, Q, **kwargs):
        super().__init__(**kwargs)
        assert width > 0 and radius > 0 
        theta0 = np.deg2rad(theta0)
        self.width = np.deg2rad(width)
        self.radius = radius
        self.theta0 = normalize_angle(theta0)

        self.Q = Q

```

the rest of the class can remain the same.

**Comment by jerabaul29** [comment]
Hi @DonsetPG !

Indeed this code was developed about 1.5 years ago, and we froze all packages then. This means that this is not the latest fenics. It is well possible that some APIs / more have changed since then. I provide a full singularity image if you want to reproduce our results.

**Comment by jerabaul29** [comment]
(i.e., this repo is a complete code and packages version freeze, and it will not be updated further; it may be updated in further work, but to ensure that all our results remain reproducible, future updates corresponding to future works will be put in separate repos).
